# Generated by Django 4.1 on 2022-08-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Uczestnik')),
                ('score', models.IntegerField(verbose_name='wynik')),
            ],
            options={
                'verbose_name': 'uczestnik',
                'verbose_name_plural': 'Tablica wyników',
            },
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'odpowiedź', 'verbose_name_plural': 'Odpowiedzi'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'pytanie', 'verbose_name_plural': 'Pytania'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='question',
            name='quote',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Cytat'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(max_length=200, verbose_name='odpowiedź'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='valid',
            field=models.BooleanField(default=False, verbose_name='poprawna odpowiedź'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Obrazek'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200, verbose_name='Pytanie'),
        ),
    ]
