# Generated by Django 4.1 on 2022-08-29 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_scoreboard_alter_answer_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScoreBoard',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quote',
        ),
    ]
