# Generated by Django 4.1 on 2022-08-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_delete_scoreboard_remove_question_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Uczestnik')),
                ('score', models.IntegerField(verbose_name='wynik')),
            ],
            options={
                'verbose_name': 'uczestnik',
                'verbose_name_plural': 'Tablica wyników',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quote',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Cytat'),
        ),
    ]
