# Generated by Django 4.1 on 2022-08-31 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_scoreboard_question_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Grupa')),
                ('hash', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Grupy pytań',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.group'),
        ),
    ]
