# Generated by Django 4.1 on 2022-08-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_group_question_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='hash',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
