# Generated by Django 4.1 on 2022-09-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_group_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='time_passed',
            field=models.DurationField(null=True),
        ),
    ]
